### ISSUE TITLE
Add Team Motto 

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#170]
A team motto is present on the registration form, however there is nowhere on the site which displays this. Would be useful to show either on the roster, the team page or both.

**Comment by blacksnotling** [comment]
Team Motto is displayed on the team page (currently in the sidebar) https://github.com/blacksnotling/HDWSBBL/commit/863f824b889b5e4765fef4b8ae51a26afde3af87
