### ISSUE TITLE
Dedicated Fans - Freebie on Team Draft

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#171]
As per the BB20 rules, teams who draft a new team get 1 dedicated fan for free. Each additional DF brought costs 10k from their treasury. 

Currently being amended manually but could do with being automated with the team registration.

**Comment by blacksnotling** [comment]
Done in https://github.com/blacksnotling/HDWSBBL/commit/368636e62ed22fef45eb85508130d4824bd61d8d
