### ISSUE TITLE
Journeymen Incorrect 

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#172]
Most JM which have been added to teams have the standard stat line, of the standard lineman or equivalent positional (normally 0-12) which is correct, however they do not have the skill "Loner (+4).

The JM for Chaos Renegades is incorrect with the stat line and the skills allocated (see ref, Kingsport Wizards).

**Comment by blacksnotling** [comment]
Fixed in https://github.com/blacksnotling/HDWSBBL/commit/478225f2fb77911597e52269aa202dcbdb3c1a31
