### ISSUE TITLE
Record Player Actions - SSP Total Shows in Tens

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#173]
When submitting the player actions, when a SSP is allocated to a player the total goes up in multiples of ten rather than a single digit (I.E, for a MVP it shows a total of 40 when it should be 4).

**Comment by blacksnotling** [comment]
@Weemanbiggins can you confirm this is fixed? It no longer happens on my end!

**Comment by blacksnotling** [comment]
confirmed fixed
