### ISSUE TITLE
Ability to Add Players for Riotous Rookies

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#174]
A new inducement, Riotous Rookies, allows for more than 16 players to be on the teams roster during the match. These players need to be added somehow to allow SSPs/Stats to be added/tracked to any of these players that carry out any action in a match or get injured by the opposition.

**Comment by blacksnotling** [comment]
Done in https://github.com/blacksnotling/HDWSBBL/commit/9cdf4adbfcd3058a831a60cf988b583b9b6bdc13
