### ISSUE TITLE
Chaos Flavour Choice

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#176]
For Chaos teams (other than Nurgle) they need the option to select which chosen deity they wish to follow (Favoured of .........). Choices are:

- Chaos Undivided
- Khorne
- Nurgle
- Slannesh
- Tzeentch

Should be shown on roster and team page (or where applicable).

**Comment by blacksnotling** [comment]
Will add as a custom taxonomy, it should only appear if the race of the team has a chosen of option. This should be auto added for Nurgle teams. I can check for the existence of either one when making the selection and force it for Nurgle

**Comment by blacksnotling** [comment]
Will need to reassign the Chosen of Nurgle teams. I can remove the current race_rule trait and that should remove it from teams / star players, and I can then just replace it with the new one on specific teams / races

**Comment by Weemanbiggins** [comment]
Can complete this manually as Stars have moved around teams they can play for (or been added).
